function supplement = import_supplement_fn(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as a matrix.
%   SUPPLEMENT = IMPORTFILE(FILENAME) Reads data from text file FILENAME
%   for the default selection.
%
%   SUPPLEMENT = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data from
%   rows STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   supplement = importfile('supplement.csv', 1, 80);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2018/02/05 10:58:53

%% Initialize variables.
delimiter = ',';
if nargin<=2
    startRow = 1;
    endRow = inf;
end

%% Read columns of data as text:
% For more information, see the TEXTSCAN documentation.
formatSpec = '%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'TextType', 'string', 'HeaderLines', startRow(1)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'TextType', 'string', 'HeaderLines', startRow(block)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Convert the contents of columns containing numeric text to numbers.
% Replace non-numeric text with NaN.
raw = repmat({''},length(dataArray{1}),length(dataArray)-1);
for col=1:length(dataArray)-1
    raw(1:length(dataArray{col}),col) = mat2cell(dataArray{col}, ones(length(dataArray{col}), 1));
end
numericData = NaN(size(dataArray{1},1),size(dataArray,2));

for col=[1,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40]
    % Converts text in the input cell array to numbers. Replaced non-numeric
    % text with NaN.
    rawData = dataArray{col};
    for row=1:size(rawData, 1)
        % Create a regular expression to detect and remove non-numeric prefixes and
        % suffixes.
        regexstr = '(?<prefix>.*?)(?<numbers>([-]*(\d+[\,]*)+[\.]{0,1}\d*[eEdD]{0,1}[-+]*\d*[i]{0,1})|([-]*(\d+[\,]*)*[\.]{1,1}\d+[eEdD]{0,1}[-+]*\d*[i]{0,1}))(?<suffix>.*)';
        try
            result = regexp(rawData(row), regexstr, 'names');
            numbers = result.numbers;
            
            % Detected commas in non-thousand locations.
            invalidThousandsSeparator = false;
            if numbers.contains(',')
                thousandsRegExp = '^\d+?(\,\d{3})*\.{0,1}\d*$';
                if isempty(regexp(numbers, thousandsRegExp, 'once'))
                    numbers = NaN;
                    invalidThousandsSeparator = true;
                end
            end
            % Convert numeric text to numbers.
            if ~invalidThousandsSeparator
                numbers = textscan(char(strrep(numbers, ',', '')), '%f');
                numericData(row, col) = numbers{1};
                raw{row, col} = numbers{1};
            end
        catch
            raw{row, col} = rawData{row};
        end
    end
end


%% Split data into numeric and string columns.
rawNumericColumns = raw(:, [1,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40]);
rawStringColumns = string(raw(:, 2));


%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),rawNumericColumns); % Find non-numeric cells
rawNumericColumns(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
supplement = table;
supplement.StateFIPS = cell2mat(rawNumericColumns(:, 1));
supplement.State = rawStringColumns(:, 1);
supplement.WICparticipantsFY2009 = cell2mat(rawNumericColumns(:, 2));
supplement.WICparticipantsFY2011 = cell2mat(rawNumericColumns(:, 3));
supplement.WICparticipantsFY2012 = cell2mat(rawNumericColumns(:, 4));
supplement.WICparticipantsFY2013 = cell2mat(rawNumericColumns(:, 5));
supplement.WICparticipantsFY2014 = cell2mat(rawNumericColumns(:, 6));
supplement.WICparticipantsFY2015 = cell2mat(rawNumericColumns(:, 7));
supplement.NationalSchoolLunchProgramparticipantsFY2009 = cell2mat(rawNumericColumns(:, 8));
supplement.NationalSchoolLunchProgramparticipantsFY2011 = cell2mat(rawNumericColumns(:, 9));
supplement.NationalSchoolLunchProgramparticipantsFY2012 = cell2mat(rawNumericColumns(:, 10));
supplement.NationalSchoolLunchProgramparticipantsFY2013 = cell2mat(rawNumericColumns(:, 11));
supplement.NationalSchoolLunchProgramparticipantsFY2014 = cell2mat(rawNumericColumns(:, 12));
supplement.NationalSchoolLunchProgramparticipantsFY2015 = cell2mat(rawNumericColumns(:, 13));
supplement.SchoolBreakfastProgramparticipantsFY2009 = cell2mat(rawNumericColumns(:, 14));
supplement.SchoolBreakfastProgramparticipantsFY2011 = cell2mat(rawNumericColumns(:, 15));
supplement.SchoolBreakfastProgramparticipantsFY2012 = cell2mat(rawNumericColumns(:, 16));
supplement.SchoolBreakfastProgramparticipantsFY2013 = cell2mat(rawNumericColumns(:, 17));
supplement.SchoolBreakfastProgramparticipantsFY2014 = cell2mat(rawNumericColumns(:, 18));
supplement.SchoolBreakfastProgramparticipantsFY2015 = cell2mat(rawNumericColumns(:, 19));
supplement.ChildandAdultCareparticpantsFY2009 = cell2mat(rawNumericColumns(:, 20));
supplement.ChildandAdultCareparticpantsFY2011 = cell2mat(rawNumericColumns(:, 21));
supplement.ChildandAdultCareparticipantsFY2012 = cell2mat(rawNumericColumns(:, 22));
supplement.ChildandAdultCareparticipantsFY2013 = cell2mat(rawNumericColumns(:, 23));
supplement.ChildandAdultCareparticipantsFY2014 = cell2mat(rawNumericColumns(:, 24));
supplement.ChildandAdultCareparticipantsFY2015 = cell2mat(rawNumericColumns(:, 25));
supplement.SummerFoodparticpantsFY2009 = cell2mat(rawNumericColumns(:, 26));
supplement.SummerFoodparticipantsFY2011 = cell2mat(rawNumericColumns(:, 27));
supplement.SummerFoodparticipantsFY2012 = cell2mat(rawNumericColumns(:, 28));
supplement.SummerFoodparticipantsFY2013 = cell2mat(rawNumericColumns(:, 29));
supplement.SummerFoodparticipantsFY2014 = cell2mat(rawNumericColumns(:, 30));
supplement.SummerFoodparticipantsFY2015 = cell2mat(rawNumericColumns(:, 31));
supplement.StatePopulation2009 = cell2mat(rawNumericColumns(:, 32));
supplement.StatePopulation2010 = cell2mat(rawNumericColumns(:, 33));
supplement.StatePopulation2011 = cell2mat(rawNumericColumns(:, 34));
supplement.StatePopulation2012 = cell2mat(rawNumericColumns(:, 35));
supplement.StatePopulation2013 = cell2mat(rawNumericColumns(:, 36));
supplement.StatePopulation2014 = cell2mat(rawNumericColumns(:, 37));
supplement.StatePopulation2015 = cell2mat(rawNumericColumns(:, 38));
supplement.StatePopulation2016 = cell2mat(rawNumericColumns(:, 39));

